//Corrected by:
// Jamie Lewis
// CST-150
// 9/16/22
// The comments and modifications made on this copied file are my own work.
// The code was copied from the assignment directions as instructed.

/* 
 * Parameters for successful program output:
 *   A Set contains no duplicate elements.
 *   A Union of 2 Sets contains all elements of both, without duplicates.
 *   Per the additional instructions provided in the Instructor's Announcements and a comment in the Program class, the original Sets should remain unchanged.
*/

// My debugging process:
// 1. Run the program to determine the output in the program's initial state.
//    Because the program uses random numbers, multiple runs are utilized to check for anomalies.
//    I note that the output fails in all 3 aspects:
//        Small Sets tend to contain duplicate element values.
//        The Union result is simply a copy of the second Set.
//        The calling Set (A) is modified by having the second Set added to it.
// 2. Examine the code for any warnings generated by Visual Studio.
// 3. Correct the warning in the Set class' "containsElement" method and run the program again.
// 4. Run the program again. The Sets no longer contain duplicate elements, but the other issues remain. 
// 5. After examining the Union method's logic, I notice that it contains 2 logic errors.
// 6. Modify the Union method to add elements of both Sets to a "temp" variable of type Set, and use it for the return.
//    This returns a Set of all elements from both Sets without modifying the original calling Set.
// 7. The Program output is now correct.

// I had also noticed that the method names in the Set class did not follow naming convention standards of starting with a capital letter.
// Correct naming scheme, and then update all method calls in the Set and Program classes.
// This was not necessarily an error, as it does not affect the program's output.

//use for IC08
//Lydia's code
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CST117_IC08_console
{
     class Program
     {
          // Updated method calls to match the methods renamed according to naming convention standards (names should begin with a capital letter).

          static void Main(string[] args)
          {
               //make some sets
               Set A = new Set();
               Set B = new Set();

               //put some stuff in the sets
               Random r = new Random();
               for (int i = 0; i < 10; i++)
               {
                    A.AddElement(r.Next(4));
                    B.AddElement(r.Next(12));
               }

               //display each set and the union
               Console.WriteLine("A: " + A);
               Console.WriteLine("B: " + B);
               Console.WriteLine("A union B: " + A.Union(B));

               //display original sets (should be unchanged)
               Console.WriteLine("After union operation");
               Console.WriteLine("A: " + A);
               Console.WriteLine("B: " + B);
          }
     }
}